### ISSUE TITLE
The WPF app raises a ClientException

### ISSUE THREAD

**Issue by shajmerchant** [Microsoft/Cognitive-Vision-Windows#10]
[10:57:13.233378]: VisionServiceClient is created
[10:57:13.267888]: Calling VisionServiceClient.AnalyzeImageAsync()...
[10:57:16.562135]: Microsoft.ProjectOxford.Vision.ClientException: Exception of type 'Microsoft.ProjectOxford.Vision.ClientException' was thrown.
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.HandleException(Exception exception)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<SendAsync>b__39_1[TRequest,TResponse](Exception e)
   at System.AggregateException.Handle(Func`2 predicate)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<SendAsync>d__39`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<AnalyzeImageAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<AnalyzeImageAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VisionAPI_WPF_Samples.AnalyzePage.<UploadAndAnalyzeImage>d__1.MoveNext() in C:\Users\smerc\Cognitive-Vision-Windows\Sample-WPF\AnalyzePage.xaml.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VisionAPI_WPF_Samples.AnalyzePage.<DoWork>d__3.MoveNext() in C:\Users\smerc\Cognitive-Vision-Windows\Sample-WPF\AnalyzePage.xaml.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at VisionAPI_WPF_Samples.ImageScenarioPage.<ShowPreviewAndDoWork>d__13.MoveNext() in C:\Users\smerc\Cognitive-Vision-Windows\Sample-WPF\ImageScenarioPage.cs:line 88

**Comment by chsienki** [comment]
HI @shajmerchant. The vision service was experiencing intermittent errors yesterday, but has now been resolved. Can you confirm if you still see the issue?

**Comment by hak59** [comment]
I'm currently running into the same problem:


Microsoft.ProjectOxford.Vision.ClientException: Exception of type 'Microsoft.ProjectOxford.Vision.ClientException' was thrown.
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.HandleException(Exception exception)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<SendAsync>b__39_1[TRequest,TResponse](Exception e)
   at System.AggregateException.Handle(Func`2 predicate)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<SendAsync>d__39`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<DescribeAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VisionAPI_WPF_Samples.DescribePage.<DescribeUrl>d__2.MoveNext() in C:\Users\humakh.REDMOND\Documents\CSSample\Cognitive-Vision-Windows\Sample-WPF\DescribePage.xaml.cs:line 115
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VisionAPI_WPF_Samples.DescribePage.<DoWork>d__3.MoveNext() in C:\Users\humakh.REDMOND\Documents\CSSample\Cognitive-Vision-Windows\Sample-WPF\DescribePage.xaml.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at VisionAPI_WPF_Samples.ImageScenarioPage.<ShowPreviewAndDoWork>d__13.MoveNext() in C:\Users\humakh.REDMOND\Documents\CSSample\Cognitive-Vision-Windows\Sample-WPF\ImageScenarioPage.cs:line 88

**Comment by batuhanersozlu** [comment]
i have the same problem.

[14:23:27.918176]: VisionServiceClient is created
[14:23:27.919175]: Calling VisionServiceClient.AnalyzeImageAsync()...
[14:23:29.277698]: Microsoft.ProjectOxford.Vision.ClientException: Exception of type 'Microsoft.ProjectOxford.Vision.ClientException' was thrown.
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.HandleException(Exception exception)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<SendAsync>b__42_1[TRequest,TResponse](Exception e)
   at System.AggregateException.Handle(Func`2 predicate)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<SendAsync>d__42`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<AnalyzeImageAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<AnalyzeImageAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VisionAPI_WPF_Samples.AnalyzePage.<AnalyzeUrl>d__2.MoveNext() in C:\Users\batuhanersozlu\Documents\GitHub\Cognitive-Vision-Windows\Sample-WPF\AnalyzePage.xaml.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VisionAPI_WPF_Samples.AnalyzePage.<DoWork>d__3.MoveNext() in C:\Users\batuhanersozlu\Documents\GitHub\Cognitive-Vision-Windows\Sample-WPF\AnalyzePage.xaml.cs:line 145
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at VisionAPI_WPF_Samples.ImageScenarioPage.<ShowPreviewAndDoWork>d__15.MoveNext() in C:\Users\batuhanersozlu\Documents\GitHub\Cognitive-Vision-Windows\Sample-WPF\ImageScenarioPage.cs:line 90

**Comment by dosama** [comment]
Same Exception Here: 
13:21:54.705380]: VisionServiceClient is created
[13:21:54.711394]: Calling VisionServiceClient.AnalyzeImageAsync()...
[13:21:55.258076]: Microsoft.ProjectOxford.Vision.ClientException: Exception of type 'Microsoft.ProjectOxford.Vision.ClientException' was thrown.
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.HandleException(Exception exception)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<SendAsync>b__42_1[TRequest,TResponse](Exception e)
   at System.AggregateException.Handle(Func`2 predicate)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<SendAsync>d__42`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<AnalyzeImageAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<AnalyzeImageAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VisionAPI_WPF_Samples.AnalyzePage.<AnalyzeUrl>d__2.MoveNext() in E:\GitRepository\Cognitive-Vision-Windows\Sample-WPF\AnalyzePage.xaml.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VisionAPI_WPF_Samples.AnalyzePage.<DoWork>d__3.MoveNext() in E:\GitRepository\Cognitive-Vision-Windows\Sample-WPF\AnalyzePage.xaml.cs:line 145
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at VisionAPI_WPF_Samples.ImageScenarioPage.<ShowPreviewAndDoWork>d__15.MoveNext() in E:\GitRepository\Cognitive-Vision-Windows\Sample-WPF\ImageScenarioPage.cs:line 90


any Help please ???

**Comment by BeshoyHindy** [comment]
i have the same issue in the 'Microsoft.ProjectOxford.Vision' project

Microsoft.ProjectOxford.Vision.ClientException: Exception of type 'Microsoft.ProjectOxford.Vision.ClientException' was thrown.
at Microsoft.ProjectOxford.Vision.VisionServiceClient.HandleException(Exception exception)
at Microsoft.ProjectOxford.Vision.VisionServiceClient.b__39_1[TRequest,TResponse](Exception e)
at System.AggregateException.Handle(Func2 predicate) at Microsoft.ProjectOxford.Vision.VisionServiceClient.<SendAsync>d__392.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at CallSite.Target(Closure , CallSite , Object )
at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
at Microsoft.ProjectOxford.Vision.VisionServiceClient.d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter1.GetResult() at VisionAPI_WPF_Samples.DescribePage.<DescribeUrl>d__2.MoveNext() in C:\Users\humakh.REDMOND\Documents\CSSample\Cognitive-Vision-Windows\Sample-WPF\DescribePage.xaml.cs:line 115 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
at VisionAPI_WPF_Samples.DescribePage.d__3.MoveNext() in C:\Users\humakh.REDMOND\Documents\CSSample\Cognitive-Vision-Windows\Sample-WPF\DescribePage.xaml.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
at VisionAPI_WPF_Samples.ImageScenarioPage.d__13.MoveNext() in C:\Users\humakh.REDMOND\Documents\CSSample\Cognitive-Vision-Windows\Sample-WPF\ImageScenarioPage.cs:line 88

**Comment by daveh551** [comment]
Same issue:

[14:41:55.845689]: VisionServiceClient is created
[14:41:55.848690]: Calling VisionServiceClient.RecognizeTextAsync()...
[14:41:56.626539]: Microsoft.ProjectOxford.Vision.ClientException: Exception of type 'Microsoft.ProjectOxford.Vision.ClientException' was thrown.
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.HandleException(Exception exception)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<SendAsync>b__42_1[TRequest,TResponse](Exception e)
   at System.AggregateException.Handle(Func`2 predicate)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<SendAsync>d__42`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<RecognizeTextAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VisionAPI_WPF_Samples.OCRPage.<RecognizeUrl>d__2.MoveNext() in D:\Users\Dave\Documents\VSProjects\Cognitive-Vision-Windows\Sample-WPF\OCRPage.xaml.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VisionAPI_WPF_Samples.OCRPage.<DoWork>d__3.MoveNext() in D:\Users\Dave\Documents\VSProjects\Cognitive-Vision-Windows\Sample-WPF\OCRPage.xaml.cs:line 149
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at VisionAPI_WPF_Samples.ImageScenarioPage.<ShowPreviewAndDoWork>d__15.MoveNext() in D:\Users\Dave\Documents\VSProjects\Cognitive-Vision-Windows\Sample-WPF\ImageScenarioPage.cs:line 90

**Comment by dulfe** [comment]
I found the same problem... and in the "Error" property inside the Exception, I can see the message: "**Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription**."

I just created the Key for "Computer Vision API" and it is valid for 30 days.

I captured the request using Fiddler and I noticed that there is no "**Ocp-Apim-Subscription-Key**" HTTP Header set... but it uses the standard **Authorization** Http Header... not sure if that is the problem or not.

**Comment by chsienki** [comment]
Could you try changing the endpoint to https://westcentralus.api.cognitive.microsoft.com/vision/v1.0 and see if the microsoft.com/cognitive keys are working?

You can change the endpoint by passing it to the VisionServiceClient when it is created. For example on the analyze page it can be changed here: https://github.com/Microsoft/Cognitive-Vision-Windows/blob/master/Sample-WPF/AnalyzePage.xaml.cs#L76

**Comment by daveh551** [comment]
I have tried the C# Getting started sample, which DOES use that endpoint, and subscription key still fails.:

    client.DefaultRequestHeaders.Add("Ocp-Apim-Subscription-Key", "<mykey>");

                // Request parameters and URI
                string requestParameters = "language=unk&detectOrientation =true";
                string uri = "https://westus.api.cognitive.microsoft.com/vision/v1.0/ocr?" + requestParameters;

Returns response code 401 with message "Access denied"

**Comment by chsienki** [comment]
That's using **westus** can you try with https://**westcentralus**.api.cognitive.microsoft.com/vision/v1.0 ?

**Comment by daveh551** [comment]
Sorry, I missed that distinction!

Yes, I changed it to westcentralus and it worked.  Thanks for your assistance.

**Comment by yaswanthpalaghat** [comment]
please try to resolve my exception:

[15:17:20.828295]: VisionServiceClient is created
[15:17:20.911300]: Calling VisionServiceClient.AnalyzeImageAsync()...
[15:17:50.338983]: Microsoft.ProjectOxford.Vision.ClientException: Exception of type 'Microsoft.ProjectOxford.Vision.ClientException' was thrown.
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.HandleException(Exception exception)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<SendAsync>b__42_1[TRequest,TResponse](Exception e)
   at System.AggregateException.Handle(Func`2 predicate)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<SendAsync>d__42`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<AnalyzeImageAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<AnalyzeImageAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VisionAPI_WPF_Samples.AnalyzePage.<UploadAndAnalyzeImage>d__1.MoveNext() in C:\Users\Mr\Desktop\vision-windows\Sample-WPF\AnalyzePage.xaml.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VisionAPI_WPF_Samples.AnalyzePage.<DoWork>d__3.MoveNext() in C:\Users\Mr\Desktop\vision-windows\Sample-WPF\AnalyzePage.xaml.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at VisionAPI_WPF_Samples.ImageScenarioPage.<ShowPreviewAndDoWork>d__15.MoveNext() in C:\Users\Mr\Desktop\vision-windows\Sample-WPF\ImageScenarioPage.cs:line 90

**Comment by cthrash** [comment]
Closing for now.  If you're are still seeing `Microsoft.ProjectOxford.Vision.ClientException`, please include the content of that exception in your issue report.  Thanks
