### ISSUE TITLE
Analyze image with domain model throws exception

### ISSUE THREAD

**Issue by infosatheesh2020** [Microsoft/Cognitive-Vision-Windows#27]
When Analyzing the image with domain model, exception is thrown below.

[13:30:02.583716]: VisionServiceClient is created
[13:30:02.590211]: Calling VisionServiceClient.AnalyzeImageInDomainAsync()...
[13:30:12.467021]: Microsoft.ProjectOxford.Vision.ClientException: Exception of type 'Microsoft.ProjectOxford.Vision.ClientException' was thrown.
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.HandleException(Exception exception)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<SendAsync>b__42_1[TRequest,TResponse](Exception e)
   at System.AggregateException.Handle(Func`2 predicate)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<SendAsync>d__42`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<AnalyzeImageInDomainAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<AnalyzeImageInDomainAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VisionAPI_WPF_Samples.AnalyzeInDomainPage.<UploadAndAnalyzeInDomainImage>d__2.MoveNext() in C:\Users\samanoh\git\Cognitive-Vision-Windows\Sample-WPF\AnalyzeInDomainPage.xaml.cs:line 115
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VisionAPI_WPF_Samples.AnalyzeInDomainPage.<DoWork>d__4.MoveNext() in C:\Users\samanoh\git\Cognitive-Vision-Windows\Sample-WPF\AnalyzeInDomainPage.xaml.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at VisionAPI_WPF_Samples.ImageScenarioPage.<ShowPreviewAndDoWork>d__15.MoveNext() in C:\Users\samanoh\git\Cognitive-Vision-Windows\Sample-WPF\ImageScenarioPage.cs:line 90

**Comment by chsienki** [comment]
Does this happen on any other calls, or just the InDomain variant?

**Comment by infosatheesh2020** [comment]
It is only with InDomain variant - both landmarks and people identification

**Comment by itorian** [comment]
Similar issue, fixed it here https://github.com/itorian/Cognitive-Vision-Windows

**Comment by cthrash** [comment]
Closing for now.  Please reactivate with ClientException details if this issue persists.
